

POST http://localhost:8000/login
Content-Type: application/json

{
  "id": 5
}

###
POST http://localhost:8000/signup
Content-Type: application/json

{
  "id": 7
}

###

DELETE http://localhost:8000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQyNjEzMTczLCJleHAiOjE2NDI2MTM0NzN9.Nk6zBkbYn9AUkT-bsainEMB6WZgIW91C1UgVTPBaLI0
###
POST http://localhost:8000/update
Content-Type: application/json

{
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjQyNjgzODU2LCJleHAiOjE2NDI2ODQxNTZ9.Aiaxk8b5ZfeT60qrFGjiZY17MfY94qtpPLYyP5O7wmc",
  "Money": 10
}
###
GET http://localhost:8000/find
###
GET http://localhost:8000/find/1

