

POST http://localhost:5000/login
Content-Type: application/json

{
  "id": 5
}

###
POST http://localhost:5000/signup
Content-Type: application/json

{
  "id": 7
}

###

DELETE http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQyNjEzMTczLCJleHAiOjE2NDI2MTM0NzN9.Nk6zBkbYn9AUkT-bsainEMB6WZgIW91C1UgVTPBaLI0
###
POST http://localhost:5000/update
Content-Type: application/json

{
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjQyNjYyMzU5LCJleHAiOjE2NDI2NjI2NTl9.LRXZmAVrcF58gqjJryWvo6A6HYqeyGN3j1r20JaKHaQ",
  "Money": 10
}
###
GET http://localhost:5000/find
###
GET http://localhost:5000/find/1

