GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqaW0iLCJpYXQiOjE2NDI2MDc2NjksImV4cCI6MTY0MjYwNzk2OX0.9f_TJ2cUgurWdDhhtAprDYdqe3uQt6JXhbcA-emih2A

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "id": 4
}

###

POST http://localhost:5000/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqaW0iLCJpYXQiOjE2NDI2MDc4NjgsImV4cCI6MTY0MjYxMTQ2OH0.95SKVuKe2-gjGj-iole0e-M3ET33rjvxTlR4j4lEw2c"
}

###

DELETE http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQyNjEzMTczLCJleHAiOjE2NDI2MTM0NzN9.Nk6zBkbYn9AUkT-bsainEMB6WZgIW91C1UgVTPBaLI0
###
POST http://localhost:5000/update
Content-Type: application/json

{
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQyNjE1OTM1LCJleHAiOjE2NDI2MTYyMzV9.a2eoNV6_xqxixg50ylmp01kWSdUk9CLtODPGONFroQ8",
  "Money": 10
}
